#!/bin/bash
clear
echo -e " SEDANG PROSES BOSKU HARAP BERSABAR"
sleep 2
echo -e ""
echo -e "=============================-Menu-============================="
echo -e "* menu         : Menampilkan Daftar Perintah"
echo -e ""
echo -e "=========================-SSH & OpenVPN-========================"
echo -e "* usernew      : Membuat Akun SSH & OpenVPN"
echo -e "* trial        : Membuat Akun Trial SSH & OpenVPN"
echo -e "* renew        : Memperpanjang Masa Aktif Akun SSH & OpenVPN"
echo -e "* deluser      : Menghapus SSH & OpenVPN"
echo -e "* cek          : Cek User Login SSH & OpenVPN"
echo -e "* member       : Menampilkan Daftar Member SSH & OpenVPN"
echo -e "* delete       : Menghapus User Expired SSH & OpenVPN"
echo -e "* autokill     : Set up Autokill SSH"
echo -e "* ceklim       : Menampilkan User Multi Login SSH"
echo -e "* restart      : Restart Service Dropbear, Squid3, OpenVPN dan SSH"
echo -e ""
echo -e "=============================-SYSTEM-=========================="
echo -e "* ram          : Cek Penggunaan Ram Dari Vps"
echo -e "* reboot       : Reboot VPS"
echo -e "* speedtest    : Speedtest VPS"
echo -e "* info         : Menampilkan Informasi Vps"
echo -e "* vnstat       : Menampilkan Penggunaan Bandwidth Vps"
echo -e "* about        : Info Script Auto Install"
echo -e "* exit         : Logout Dari VPS "
echo -e ""
echo -e "==============================================================="
echo -e "X-IDSSH"